node .\parser.js .\htmlConverted\Chapter_1.htm .\parsed\chap1.json
node .\parser.js .\htmlConverted\Chapter_4.html .\parsed\chap4.json
node .\parser.js .\htmlConverted\Chapter_5.html .\parsed\chap5.json
node .\parser.js .\htmlConverted\Chapter_6.html .\parsed\chap6.json
node .\parser.js .\htmlConverted\Chapter_7.html .\parsed\chap7.json
node .\parser.js .\htmlConverted\Chapter_8.html .\parsed\chap8.json
node .\parser.js .\htmlConverted\Chapter_11.html .\parsed\chap11.json
node .\parser.js .\htmlConverted\Chapter_13.html .\parsed\chap13.json
node .\parser.js .\htmlConverted\Chapter_14.html .\parsed\chap14.json